all: os-image

boot.bin: boot.asm
	nasm -f bin boot.asm -o boot.bin

kernel.bin: kernel.c
	gcc -ffreestanding -m32 -c kernel.c -o kernel.o
	ld -o kernel.bin -T linker.ld --oformat binary kernel.o

os-image: boot.bin kernel.bin
	cat boot.bin kernel.bin > os-image.bin

run: os-image
	qemu-system-i386 -fda os-image.bin

clean:
	rm -f *.bin *.o os-image.bin