all: os-image.bin

boot.bin: boot.asm
	nasm -f bin boot.asm -o boot.bin

kernel.o: kernel.c
	gcc -ffreestanding -m32 -c kernel.c -o kernel.o

kernel.bin: kernel.o
	ld -m elf_i386 -o kernel.bin -T linker.ld --oformat binary kernel.o

os-image.bin: boot.bin kernel.bin
	cat boot.bin kernel.bin > os-image.bin

run: os-image.bin
	qemu-system-i386 -fda os-image.bin -monitor stdio

debug: os-image.bin
	qemu-system-i386 -fda os-image.bin -S -gdb tcp::1234

clean:
	rm -f *.bin *.o os-image.bin