name: Build OS Image

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm gcc-multilib qemu-system-i386

      - name: Build os-image
        run: |
          cd mi_so_completo
          make clean
          make

      - name: Upload os-image.bin artifact
        uses: actions/upload-artifact@v4
        with:
          name: os-image
          path: mi_so_completo/os-image.bin
